/* ============================================================
   ERIC OLIVIER MARIO — Language System (EN / FR)
   ============================================================ */

const translations = {
  en: {
    /* ── Nav ── */
    'nav.music': 'Music',
    'nav.journey': 'The Journey',
    'nav.apply': 'Apply',
    'nav.about': 'About',

    /* ── Newsletter / Footer (shared) ── */
    'newsletter.label': 'Stay close',
    'newsletter.sub': 'New music, reflections, and occasional openings. Only when there is something real to say.',
    'newsletter.name-placeholder': 'Your name',
    'newsletter.email-placeholder': 'Your email',
    'newsletter.btn': 'Subscribe',

    /* ── index.html ── */
    'home.tagline': 'Sound as a path inwards',
    'home.subtitle': 'Melodic electronic music and mentorship exploring sound as a path of self-discovery',
    'home.begin': 'Begin',
    'home.pathway1.label': '01',
    'home.pathway1.title': 'The Music',
    'home.pathway1.desc': 'Three movements from darkness into light.',
    'home.pathway1.cta': 'Explore',
    'home.pathway2.label': '02',
    'home.pathway2.title': 'The Journey',
    'home.pathway2.desc': 'Training for artists ready to create from who they are.',
    'home.pathway2.cta': 'Learn More',
    'home.pathway3.label': '03',
    'home.pathway3.title': 'Work With Me',
    'home.pathway3.desc': 'Anything you wanna know — I am here to help.',
    'home.pathway3.cta': 'Apply',
    'home.pos.p1': 'Some people map a journey. I\'m still on mine.',
    'home.pos.p2': 'Music found me during one of the quietest periods of my life — not as a career move, but as a way through. What began as an escape became a language. What became a language became a body of work.',
    'home.pos.p3': 'Eric Olivier Mario is electronic music rooted in feeling — melodic, atmospheric, built for the kind of listening that turns inward. My compositions don\'t follow a genre so much as a direction: from the weight of what is unresolved, toward the openness of what becomes possible.',
    'home.pos.p4': 'That direction has a shape. Three movements. A journey from C minor to D major — from darkness into light.',
    'home.pos.p5': 'And because I\'m still walking it, I guide other artists through the same arc. Not from above. From beside.',
    'home.invitation': 'If you make music and feel the pull toward something deeper than technique — toward <em>who you actually are</em> when you create — this space was made for you.',
    'home.invitation.cta': 'Discover My Music',

    /* ── music.html ── */
    'music.label': 'Unfolding',
    'music.heading': 'Three movements.',
    'music.microcopy': 'Tracks that move from darkness into light.',
    'music.arc.label': 'The Arc behind my album — Unfolding',
    'music.arc.cta': '▶ Each number is a track. Click to listen.',
    'music.arc.panel.select': 'Select a chapter',
    'music.arc.mv1.label': 'Movement I',
    'music.arc.mv1.sub': 'The Descent Beneath',
    'music.arc.mv2.label': 'Movement II',
    'music.arc.mv2.sub': 'The Threshold Continuum',
    'music.arc.mv3.label': 'Movement III',
    'music.arc.mv3.sub': 'The Return Release',
    'music.arc.footer': 'From C minor to D major.<br>From darkness held — to light arrived.<br><em style="font-style:italic; opacity:0.7;">I explain every movement below</em>',
    'music.mv1.label': 'Movement I',
    'music.mv1.title': 'The Descent Beneath',
    'music.mv1.subtitle': 'Inward Motion',
    'music.mv1.desc': 'The music you make when you\'re still underground — feeling your way through the dark without knowing what\'s ahead.',
    'music.mv1.quote': '"The first step is always down. Before you find anything, you lose the story you were told about yourself."',
    'music.mv2.label': 'Movement II',
    'music.mv2.title': 'The Threshold Continuum',
    'music.mv2.subtitle': 'Music to Stay With',
    'music.mv2.desc': 'The suspended place between who you were and who you\'re becoming. Neither darkness nor light — pure transition.',
    'music.mv2.quote': '"Something stirs. Not understanding yet — just the sense that what was solid has begun to move."',
    'music.mv3.label': 'Movement III',
    'music.mv3.title': 'The Return Release',
    'music.mv3.subtitle': 'When the Weight Lifts',
    'music.mv3.desc': 'The music that arrives when you stop fighting. Not happiness — something quieter and more permanent than that.',
    'music.mv3.quote': '"Not the end. The beginning of creating from a place you no longer need to explain."',
    'music.showcase.intro': 'The arc above maps the album as a whole — nine tracks, three movements.<br>Below, a few pieces that best represent the sound: where it comes from, where it goes.<br><em>Listen before you read further.</em>',
    'music.bridge.heading': 'The music beyond this page lives across these spaces —',
    'music.bridge.credits1': 'Supported by Paul van Dyk · Kyau &amp; Albert · Lumidelic',
    'music.bridge.credits2': 'Released on Emergent · Soluna Music · Synth Collective · Synthdelic · Saturo · Summer Melody',
    'music.bridge.spotify': 'Listen on Spotify',
    'music.bridge.youtube': 'Watch on YouTube',
    'music.bridge.journey': 'Explore The Journey',

    /* ── about.html ── */
    'about.hero.title': 'Who I am and why it matters to your music',
    'about.bio.p1': 'Sound was the first language that made sense to me.',
    'about.bio.p2': 'My parents gave me a classical guitar at seven. I didn\'t become a virtuoso — but I became someone who understood that music could carry what words couldn\'t hold. Through adolescence, through songs written in two languages, through years of listening to electronic music and feeling something shift inside me I couldn\'t name — that understanding deepened quietly, without direction.',
    'about.bio.p3': 'Production found me much later, during one of the quietest and most disorienting periods of my life. COVID stripped everything back — the routine, the forward motion, the noise that kept certain questions at bay. Left alone with myself, I stopped circling and started creating. Not because I had a vision. Because I needed somewhere to put what I was feeling.',
    'about.bio.p4': 'That\'s where Eric Olivier Mario began.',
    'about.bio.p5': 'What followed wasn\'t a career path. It was a practice. Learning by listening obsessively, experimenting without a roadmap, and gradually — slowly — finding a language that was mine. My album <em>Unfolding</em> is the sound of that journey made visible: atmospheric, emotional, built from textures and space rather than formulas.',
    'about.bio.p6': 'Over the years, the music has found its way to labels that share a similar sense of direction — Emergent, Soluna Music, Synth Collective, Synthdelic, Saturo, Summer Melody among them. It has received support from artists whose work I grew up listening to — Paul van Dyk, Kyau &amp; Albert — and has led to genuine creative exchange with artists like Lumidelic and others across those communities.',
    'about.bio.p7': 'I mention this not to establish credentials, but because it matters to the work I do with students. The path from making music in private to having it heard, respected, and supported by people you admire — that journey is real. I\'ve walked it. I know what it takes, and I know what it costs.',
    'about.bio.p8': 'That path is exactly why I work with artists the way I do.',
    'about.bio.p9': 'I know what it feels like to have something real inside you and not yet know how to release it. I know the frustration of technical overwhelm — the moment a track stops becoming what you heard in your head and starts feeling like a problem to solve. I know the particular silence of self-doubt that arrives not when you\'re bad at this, but when you care deeply about getting it right.',
    'about.bio.p10': 'I\'ve sat in that space. I still do sometimes.',
    'about.bio.p11': 'What I\'ve learned — and what I bring into every session — is that what moves you forward isn\'t more plugins, more tutorials, or more technique. It\'s developing a real relationship with your own creative process. Understanding where your sound actually comes from. Building the capacity to stay present when the work gets uncomfortable.',
    'about.bio.p12': 'What I offer isn\'t a curriculum. It\'s a space — unhurried, personal, built around where you actually are. I listen to your music. I also listen to you. Those two things are not separate.',
    'about.bio.p13': 'I didn\'t come to this from above. I came from the same place you\'re standing now.',
    'about.bio.p14': 'If that feels like what you\'ve been looking for — you\'re in the right place.',
    'about.lineage.label': 'Lineage',
    'about.lineage.p1': 'My influences don\'t sit neatly in a genre. They live in the space between things — the pause before a drop, the silence that makes a sound feel larger than it is, the moment in a track where time seems to slow down and breathe.',
    'about.lineage.p2': 'I grew up between two languages, two cultures, two ways of hearing the world. That in-between place never felt like a gap. It felt like a doorway. French sensibility taught me restraint. The music I fell in love with — melodic, hypnotic, emotionally vast — taught me that you can move a dancefloor and a soul at the same time.',
    'about.lineage.p3': 'My productions are shaped by film scoring as much as electronic music. By the architecture of sound — how atmosphere is built layer by layer, how emotion lives in texture and timing rather than melody alone. I\'m drawn to music that doesn\'t announce itself but settles into you slowly, that rewards the kind of listening most people have forgotten how to do.',
    'about.lineage.p4': 'I didn\'t study music formally. I studied feeling — through years of sitting with difficult emotions, paying attention to what moved me and why, learning to stay present when the creative process got uncomfortable. That practice is woven into every session I hold. It\'s what makes the work go somewhere real.',
    'about.bridge': 'If any of this resonates — not with your mind, but with something underneath it —',
    'about.bridge.cta': 'Explore The Journey',

    /* ── the-journey.html ── */
    'journey.label': 'The Journey',
    'journey.heading': 'Training for artists<br>who are ready to stop<br>performing and start arriving.',
    'journey.microcopy': 'This is not education. It is excavation.',
    'journey.phil.p1': 'Most artist development focuses on skill, audience, and output.',
    'journey.phil.p2': 'This work focuses on something underneath all of that: who you are when you create.',
    'journey.phil.p3': 'The Journey is a guided passage through two territories — from finding your creative foundation and reconnecting to your authentic voice, to inhabiting presence through sound and building something entirely yours.',
    'journey.phil.p4': 'It is not for everyone. It is for artists who already sense that their next evolution is not technical.',
    'journey.gains.title': 'What shifts when you do this work',
    'journey.gains.1': 'A clearer sense of who you are when you create — and why that matters more than any technique',
    'journey.gains.2': 'The ability to finish what you start, because you\'re no longer creating against yourself',
    'journey.gains.3': 'A sound that is recognisably yours — not assembled from references, but built from what you actually carry',
    'journey.gains.4': 'The confidence to sit with uncertainty in the creative process without abandoning the work',
    'journey.gains.5': 'A relationship with music that feels sustainable — not driven by output, but by genuine presence',
    'journey.mod1.label': 'Module I',
    'journey.mod1.title': 'Rooted Creation',
    'journey.mod1.tagline': 'Discover your creative foundation — a single session to reconnect with your authentic voice.',
    'journey.mod1.body1': 'A 2-hour discovery session for new students. Together we unearth your influences, build a project from scratch in Logic Pro or the DAW of your choice, and define your sonic direction.',
    'journey.mod1.body2': 'You walk away with a reference track, a creative brief defining your artist identity, and a next steps roadmap.',
    'journey.mod1.transform': 'From starting with nothing \u00a0→\u00a0 to building from what you actually carry.',
    'journey.mod1.format': 'Single session \u00a0·\u00a0 2 hours \u00a0·\u00a0 1-to-1 \u00a0·\u00a0 £69',
    'journey.mod1.cta': 'Explore Module I',
    'journey.mod2.label': 'Module II',
    'journey.mod2.title': 'Presence &amp; Sound',
    'journey.mod2.tagline': 'Building depth through weekly practice — crafting a complete track that is entirely yours.',
    'journey.mod2.body1': 'Four weekly 1-to-1 sessions that take you from grounding and listening to designing your own sounds and completing a full composition. Each week builds on the last.',
    'journey.mod2.body2': 'You walk away with a completed reference track, a personal sound palette, a listening log, and direct access to Eric throughout via phone and WhatsApp.',
    'journey.mod2.transform': 'From scattered ideas \u00a0→\u00a0 to a cohesive creation rooted in who you are.',
    'journey.mod2.format': '4 weekly sessions \u00a0·\u00a0 1-to-1 \u00a0·\u00a0 Async support \u00a0·\u00a0 £199/month',
    'journey.mod2.cta': 'Explore Module II',
    'journey.space.label': 'The Space',
    'journey.fit.yes.title': 'This space is for artists who\u00a0—',
    'journey.fit.yes.1': 'Are seeking personal transformation through their creative work',
    'journey.fit.yes.2': 'Want to learn music production from the ground up while developing their unique voice',
    'journey.fit.yes.3': 'Are ready to expand their creativity and build a cohesive sonic universe',
    'journey.fit.yes.4': 'Are willing to slow down to go deeper',
    'journey.fit.yes.5': 'Are drawn to this page for reasons they may not fully articulate yet',
    'journey.fit.no.title': 'This is not the right fit if you\u00a0—',
    'journey.fit.no.1': 'Are only looking for production techniques without the inner work',
    'journey.fit.no.2': 'Want to grow your audience or streaming numbers',
    'journey.fit.no.3': 'Need external validation to continue creating',
    'journey.fit.no.4': 'Are not willing to invest time in weekly practice',
    'journey.fit.no.5': 'Want a curriculum without the creative self-discovery',
    'journey.apply.p1': 'Enrollment is by application only.',
    'journey.apply.p2': 'This is not about gatekeeping. It is about ensuring the space holds what it needs to hold.',
    'journey.apply.btn': 'Apply',

    /* ── apply.html ── */
    'apply.label': 'Application',
    'apply.heading': 'Begin here.',
    'apply.subheading': 'Before we begin working together, a few questions — if you feel resonance with this work, you are warmly invited to apply. There is no expectation — only a conversation.',
    'apply.microcopy': 'There are no right answers. Only honest ones.',
    'apply.step1.q': 'What is your name and artist name?',
    'apply.step1.hint': 'If they are the same, that is fine.',
    'apply.step1.name': 'Your name',
    'apply.step1.artist': 'Artist name (if different)',
    'apply.step2.q': 'Describe your creative practice in a few sentences.',
    'apply.step2.hint': 'What do you make? How long have you been making it?',
    'apply.step2.placeholder': 'I make...',
    'apply.step3.q': 'Where are you right now in your artistic life?',
    'apply.step3.hint': 'Not your career — your inner relationship to creating.',
    'apply.step3.placeholder': 'Right now I am...',
    'apply.step4.q': 'What brought you to this page?',
    'apply.step4.hint': 'Be as specific or as abstract as you like.',
    'apply.step4.placeholder': 'I arrived here because...',
    'apply.step5.q': 'What would need to shift in your life to make space for this kind of work over the next 4–6 weeks?',
    'apply.step5.placeholder': 'To make space, I would need to...',
    'apply.step6.q': 'Which module resonates most right now?',
    'apply.step6.mod1': 'Module 1 — Rooted Creation — £69',
    'apply.step6.mod2': 'Module 2 — Presence &amp; Sound — 4 week program — £199',
    'apply.step6.unsure': 'I am not sure yet — I would like guidance',
    'apply.step7.q': 'How did you find this space?',
    'apply.step7.youtube': 'YouTube',
    'apply.step7.streaming': 'Spotify / Apple Music',
    'apply.step7.friend': 'A friend or collaborator',
    'apply.step7.social': 'Social media',
    'apply.step7.other': 'Something else',
    'apply.step7.other-placeholder': 'If something else, how?',
    'apply.step8.q': 'How should we reach you?',
    'apply.step8.email': 'Email address',
    'apply.step8.conv': 'How would you prefer to have a conversation?',
    'apply.step8.video': 'Video call',
    'apply.step8.voice': 'Voice call',
    'apply.step8.written': 'Written exchange',
    'apply.step9.q': 'Is there anything else you want to share before we begin?',
    'apply.step9.hint': 'This is optional.',
    'apply.btn.back': 'Back',
    'apply.btn.continue': 'Continue',
    'apply.btn.submit': 'Submit Application',
    'apply.confirm.heading': 'Thank you.',
    'apply.confirm.p1': 'You will hear back within 7 days.',
    'apply.confirm.p2': 'If there is alignment, we will schedule a conversation. If not, you will receive an honest and respectful reply.',
    'apply.confirm.microcopy': 'No automated responses. Every application is read personally.',
    'apply.confirm.return': 'Return to the music',

    /* ── module-1.html ── */
    'm1.label': 'Module I',
    'm1.title': 'Rooted Creation',
    'm1.microcopy': 'Discover your creative foundation — a single session to begin.',
    'm1.where-begin.h': 'Where you begin',
    'm1.where-begin.p1': 'You feel the pull to create but the tools feel unfamiliar, or the sounds you reach for don\'t feel like yours. Maybe you are starting from scratch entirely.',
    'm1.where-begin.p2': 'There is a gap between who you are and what you make — and you are ready to close it.',
    'm1.where-leads.h': 'Where this leads',
    'm1.where-leads.p1': 'In a single 2-hour session, you reconnect with your authentic creative voice — exploring your identity, your influences, and what exists underneath them.',
    'm1.where-leads.p2': 'You leave with a first project built from scratch in Logic Pro, a clearer sense of direction, and a written summary of your next steps.',
    'm1.session.title': 'What happens inside the session',
    'm1.part1.label': 'Part 1',
    'm1.part1.theme': 'Unearthing',
    'm1.part1.desc': 'We begin by discovering your authentic voice — exploring your creativity, your past influences, and what exists underneath them. Finding the artistic identity and references that are truly yours.',
    'm1.part2.label': 'Part 2',
    'm1.part2.theme': 'Creation',
    'm1.part2.desc': 'You learn to create a project from scratch in Logic Pro. I teach you the techniques to start putting your ideas together — session setup, signal flow, and the essentials of building sound from nothing.',
    'm1.part3.label': 'Part 3',
    'm1.part3.theme': 'First Movements',
    'm1.part3.desc': 'Translating your insights into sound. Experimenting with initial compositions that reflect your unique emotional landscape — slowly, without judgment, without reference.',
    'm1.walkaway.label': 'What you walk away with',
    'm1.walkaway.1': 'A reference track that reflects your emerging sound identity',
    'm1.walkaway.2': 'A first Logic Pro project started from scratch — your very first sonic sketch',
    'm1.walkaway.3': 'A recorded session summary capturing your key insights, references, and direction',
    'm1.walkaway.4': 'Clarity on your 3 core influences and how to translate them into your own sound',
    'm1.walkaway.5': 'A creative brief — a one-page document defining your artist identity, mood, and sonic direction',
    'm1.walkaway.6': 'A next steps roadmap — what to work on in the weeks ahead',
    'm1.walkaway.7': 'Confidence that you have something real to build from',
    'm1.after.label': 'After this module you will',
    'm1.after.1': 'Complete one finished track',
    'm1.after.2': 'Understand your harmonic language',
    'm1.after.3': 'Develop a personal sonic identity',
    'm1.container.label': 'The container',
    'm1.container.format-label': 'Format',
    'm1.container.format-value': '1-to-1<br>with Eric',
    'm1.container.duration-label': 'Duration',
    'm1.container.duration-value': 'Single session<br>2 hours',
    'm1.container.prereq-label': 'Prerequisite',
    'm1.container.prereq-value': 'None — this is<br>where you start',
    'm1.investment.label': 'Investment',
    'm1.investment.price': '£69',
    'm1.investment.desc': 'A single 2-hour discovery session. You leave with a project started, a written summary, and clear next steps.',
    'm1.investment.microcopy': 'This is the entry point into The Journey — no prerequisites, no commitment beyond this session.',
    'm1.investment.btn': 'Book Module I',
    'm1.back': 'All Modules',

    /* ── module-2.html ── */
    'm2.label': 'Module II',
    'm2.title': 'Presence &amp; Sound',
    'm2.microcopy': 'Four weeks of depth, practice, and presence — building a track that is entirely yours.',
    'm2.where-begin.h': 'Where you begin',
    'm2.where-begin.p1': 'You have the foundation from Module I. You understand your tools, you can shape sound. Now you are ready to go deeper — to cultivate a real connection to sound through awareness and presence.',
    'm2.where-begin.p2': 'The techniques are there. What is needed now is depth, practice, and the patience to let something whole emerge.',
    'm2.where-leads.h': 'Where this leads',
    'm2.where-leads.p1': 'A completed track — designed as a reference piece for your musical journey. You will use the techniques and tools from Module I to craft your unique sound, working from embodied presence rather than reactive habit.',
    'm2.where-leads.p2': 'By the end, you have not just learned — you have created something that is entirely yours.',
    'm2.weeks.title': 'What happens inside',
    'm2.week1.label': 'Week 1',
    'm2.week1.theme': 'Arriving',
    'm2.week1.desc': 'Grounding yourself in the present moment, creating a strong foundation for the creative work ahead. You leave with a grounding ritual you can repeat before every production session, and a new Logic Pro session template set up to your workflow.',
    'm2.week2.label': 'Week 2',
    'm2.week2.theme': 'Listening',
    'm2.week2.desc': 'Active listening before shaping sounds. You build a personal listening log — an annotated report on 1–3 reference tracks broken down sonically. Understanding how atmosphere, space, and emotion are constructed in your favourite music or your own work.',
    'm2.week3.label': 'Week 3',
    'm2.week3.theme': 'Body',
    'm2.week3.desc': 'Exploring how movement and physicality influence your creative expression. You build a completed sound palette — a folder of original sounds, samples, and textures you have designed yourself, alongside samples I share with you. First draft of a track arrangement built around those sounds.',
    'm2.week4.label': 'Week 4',
    'm2.week4.theme': 'Integration',
    'm2.week4.desc': 'Blending everything into a completed reference track — a full composition that represents your sound world. You receive a feedback recording from Eric reviewing the track with timestamp notes, and a progress reflection document summarising your journey, breakthroughs, and next chapter.',
    'm2.walkaway.label': 'What you walk away with',
    'm2.walkaway.1': 'A grounding ritual or pre-session practice you can repeat before every production session',
    'm2.walkaway.2': 'A Logic Pro session template set up to your workflow',
    'm2.walkaway.3': 'A personal listening log — annotated sonic breakdown of reference tracks',
    'm2.walkaway.4': 'A completed sound palette — original sounds, samples, and textures you have designed',
    'm2.walkaway.5': 'A completed reference track — a full composition that represents your sound world',
    'm2.walkaway.6': 'A feedback recording from Eric reviewing your track with timestamp notes',
    'm2.walkaway.7': 'A progress reflection document summarising your journey, breakthroughs, and next chapter',
    'm2.walkaway.8': 'Direct access to Eric via phone and WhatsApp for async support throughout',
    'm2.after.label': 'After this module you will',
    'm2.after.1': 'Have a reference track and template you can use for all your projects',
    'm2.after.2': 'Understand your harmonic language',
    'm2.after.3': 'Develop a personal sonic identity',
    'm2.after.4': 'Design a complete sound palette to create EPs and albums',
    'm2.after.5': 'Get constant feedback from Eric whenever needed',
    'm2.container.label': 'The container',
    'm2.container.format-label': 'Format',
    'm2.container.format-value': '1-to-1<br>with Eric',
    'm2.container.duration-label': 'Duration',
    'm2.container.duration-value': '4 weekly<br>sessions',
    'm2.container.prereq-label': 'Prerequisite',
    'm2.container.prereq-value': 'Module I or<br>equivalent depth',
    'm2.investment.label': 'Investment',
    'm2.investment.price': '£199<span style="font-size: 1rem; color: var(--text-muted);">/month</span>',
    'm2.investment.desc': 'Four weekly 1-to-1 sessions with Eric. You walk away with a completed reference track, a personal sound palette, and direct async support throughout.',
    'm2.investment.microcopy': 'If cost is a genuine barrier and the readiness is real, that conversation is welcome too.',
    'm2.investment.btn': 'Apply for Module II',
    'm2.back': 'All Modules',
  },

  fr: {
    /* ── Nav ── */
    'nav.music': 'Musique',
    'nav.journey': 'Le Parcours',
    'nav.apply': 'Postuler',
    'nav.about': 'À propos',

    /* ── Newsletter / Footer (shared) ── */
    'newsletter.label': 'Restons en lien',
    'newsletter.sub': 'Nouvelles musiques, réflexions et ouvertures occasionnelles. Seulement quand il y a vraiment quelque chose à partager.',
    'newsletter.name-placeholder': 'Votre prénom',
    'newsletter.email-placeholder': 'Votre email',
    'newsletter.btn': 'S\'abonner',

    /* ── index.html ── */
    'home.tagline': '« Le son comme chemin vers soi »',
    'home.subtitle': '« Musique électronique mélodique et mentorat — explorer le son comme voie de découverte intérieure »',
    'home.begin': 'Commencer',
    'home.pathway1.label': '01',
    'home.pathway1.title': 'La Musique',
    'home.pathway1.desc': '« Trois mouvements : de l\'ombre à la lumière »',
    'home.pathway1.cta': 'Explorer',
    'home.pathway2.label': '02',
    'home.pathway2.title': 'Le Parcours',
    'home.pathway2.desc': 'Une formation pour les artistes prêts à créer depuis qui ils sont vraiment.',
    'home.pathway2.cta': 'En savoir plus',
    'home.pathway3.label': '03',
    'home.pathway3.title': 'Travailler avec moi',
    'home.pathway3.desc': 'Tout ce que vous voulez savoir — je suis là pour vous aider.',
    'home.pathway3.cta': 'Postuler',
    'home.pos.p1': 'Certaines personnes tracent un chemin. Moi, je suis encore en train de parcourir le mien.',
    'home.pos.p2': 'La musique m\'a trouvé pendant l\'une des périodes les plus silencieuses de ma vie — non pas comme un choix de carrière, mais comme un passage. Ce qui avait commencé comme une échappatoire est devenu un langage. Et ce langage est devenu un corps d\'œuvre.',
    'home.pos.p3': 'Eric Olivier Mario est une musique électronique enracinée dans le ressenti — mélodique, atmosphérique, pensée pour une écoute qui se tourne vers l\'intérieur. Mes compositions ne suivent pas tant un genre qu\'une direction : partir du poids de ce qui reste irrésolu, pour aller vers l\'ouverture de ce qui devient possible.',
    'home.pos.p4': 'Cette direction a une forme. Trois mouvements. Un voyage du do mineur vers le ré majeur — de l\'obscurité vers la lumière.',
    'home.pos.p5': 'Et parce que je suis encore en train de le parcourir, j\'accompagne d\'autres artistes sur ce même arc. Non pas au-dessus d\'eux. À leurs côtés.',
    'home.invitation': 'Si vous faites de la musique et ressentez l\'appel vers quelque chose de plus profond que la technique — vers <em>qui vous êtes vraiment</em> lorsque vous créez — cet espace a été fait pour vous.',
    'home.invitation.cta': 'Découvrir ma musique',

    /* ── music.html ── */
    'music.label': 'Unfolding',
    'music.heading': 'Trois mouvements.',
    'music.microcopy': 'Des morceaux qui vont de l\'ombre à la lumière.',
    'music.arc.label': 'L\'arc narratif derrière mon album — Unfolding',
    'music.arc.cta': '▶ Chaque numéro correspond à un morceau. Cliquez pour écouter.',
    'music.arc.panel.select': 'Sélectionnez un chapitre',
    'music.arc.mv1.label': 'Mouvement I',
    'music.arc.mv1.sub': 'La Descente au-dedans',
    'music.arc.mv2.label': 'Mouvement II',
    'music.arc.mv2.sub': 'Le Seuil du Continuum',
    'music.arc.mv3.label': 'Mouvement III',
    'music.arc.mv3.sub': 'Le Retour et la Libération',
    'music.arc.footer': 'Du do mineur au ré majeur.<br>De l\'ombre retenue — à la lumière atteinte.<br><em style="font-style:italic; opacity:0.7;">J\'explique chaque mouvement ci-dessous.</em>',
    'music.mv1.label': 'Mouvement I',
    'music.mv1.title': 'La Descente Intérieure',
    'music.mv1.subtitle': 'Mouvement vers l\'intérieur',
    'music.mv1.desc': 'La musique que l\'on crée quand on est encore souterrain — à tâtons dans l\'obscurité, sans savoir ce qui nous attend.',
    'music.mv1.quote': '« Le premier pas est toujours vers le bas. Avant de trouver quoi que ce soit, on perd l\'histoire qu\'on nous avait racontée sur nous-mêmes. »',
    'music.mv2.label': 'Mouvement II',
    'music.mv2.title': 'Le Continuum du Seuil',
    'music.mv2.subtitle': 'Une musique pour rester',
    'music.mv2.desc': 'Un lieu suspendu entre qui vous étiez et qui vous devenez. Ni obscurité ni lumière — pure transition.',
    'music.mv2.quote': '« Quelque chose s\'éveille. Pas encore de compréhension — juste la sensation que ce qui était solide a commencé à bouger. »',
    'music.mv3.label': 'Mouvement III',
    'music.mv3.title': 'La Libération du Retour',
    'music.mv3.subtitle': 'Quand le poids se lève',
    'music.mv3.desc': 'La musique qui arrive quand on arrête de lutter. Pas le bonheur — quelque chose de plus silencieux et de plus permanent que cela.',
    'music.mv3.quote': '« Pas une fin. Le début de créer depuis un endroit qu\'on n\'a plus besoin d\'expliquer. »',
    'music.showcase.intro': 'L\'arc ci-dessus cartographie l\'album dans son ensemble — neuf titres, trois mouvements.<br>Ci-dessous, quelques morceaux qui représentent le mieux le son : d\'où il vient, et où il va.<br><em>Écoutez avant de continuer votre lecture.</em>',
    'music.bridge.heading': '« La musique au-delà de cette page vit à travers ces espaces — »',
    'music.bridge.credits1': 'Soutenu par Paul van Dyk · Kyau &amp; Albert · Lumidelic',
    'music.bridge.credits2': 'Sorti sur Emergent · Soluna Music · Synth Collective · Synthdelic · Saturo · Summer Melody',
    'music.bridge.spotify': 'Écouter sur Spotify',
    'music.bridge.youtube': 'Regarder sur YouTube',
    'music.bridge.journey': 'Explorer Le Parcours',

    /* ── about.html ── */
    'about.hero.title': 'Qui je suis et pourquoi cela compte pour votre musique',
    'about.bio.p1': 'Le son a été le premier langage qui avait du sens pour moi.',
    'about.bio.p2': 'Mes parents m\'ont offert une guitare classique à sept ans. Je ne suis pas devenu virtuose — mais je suis devenu quelqu\'un qui comprenait que la musique pouvait porter ce que les mots ne pouvaient pas contenir. À travers l\'adolescence, à travers des chansons écrites en deux langues, à travers des années d\'écoute de musique électronique et le sentiment que quelque chose bougeait en moi sans que je puisse le nommer — cette compréhension s\'est approfondie tranquillement, sans direction.',
    'about.bio.p3': 'La production m\'a trouvé bien plus tard, pendant l\'une des périodes les plus silencieuses et déroutantes de ma vie. Le COVID a tout dépouillé — la routine, le mouvement vers l\'avant, le bruit qui maintenait certaines questions à distance. Seul avec moi-même, j\'ai cessé de tourner en rond et j\'ai commencé à créer. Pas parce que j\'avais une vision. Parce que j\'avais besoin d\'un endroit pour déposer ce que je ressentais.',
    'about.bio.p4': 'C\'est là que Eric Olivier Mario a commencé.',
    'about.bio.p5': 'Ce qui a suivi n\'était pas un chemin de carrière. C\'était une pratique. Apprendre en écoutant obsessionnellement, expérimenter sans feuille de route et, progressivement — lentement — trouver un langage qui m\'était propre. Mon album <em>Unfolding</em> est le son de ce voyage rendu visible : atmosphérique, émotionnel, construit à partir de textures et d\'espaces plutôt que de formules.',
    'about.bio.p6': 'Au fil des années, cette musique a trouvé sa place chez des labels partageant un sens similaire de direction — Emergent, Soluna Music, Synth Collective, Synthdelic, Saturo, Summer Melody, parmi d\'autres. Elle a reçu le soutien d\'artistes que j\'écoutais en grandissant — Paul van Dyk, Kyau &amp; Albert — et a conduit à de véritables échanges créatifs avec des artistes comme Lumidelic et d\'autres au sein de ces communautés.',
    'about.bio.p7': 'Je mentionne cela non pour établir des références, mais parce que cela compte pour le travail que je fais avec mes étudiants. Le chemin entre créer de la musique en privé et la voir écoutée, respectée et soutenue par des personnes que vous admirez — ce chemin est réel. Je l\'ai parcouru. Je sais ce que cela demande et ce que cela coûte.',
    'about.bio.p8': 'C\'est exactement ce chemin qui explique pourquoi je travaille avec les artistes de cette manière.',
    'about.bio.p9': 'Je sais ce que ça fait d\'avoir quelque chose de réel en soi et de ne pas encore savoir comment le libérer. Je connais la frustration de la surcharge technique — le moment où un morceau cesse de devenir ce que vous entendiez dans votre tête et commence à ressembler à un problème à résoudre. Je connais le silence particulier du doute de soi qui survient non pas parce que vous êtes mauvais·e, mais parce que vous tenez profondément à bien faire.',
    'about.bio.p10': 'J\'ai été dans cet espace. J\'y suis encore parfois.',
    'about.bio.p11': 'Ce que j\'ai appris — et ce que j\'apporte dans chaque session — c\'est que ce qui vous fait avancer n\'est pas plus de plugins, plus de tutoriels, ou plus de technique. C\'est développer une vraie relation avec votre propre processus créatif, comprendre d\'où vient réellement votre son et acquérir la capacité de rester présent quand le travail devient inconfortable.',
    'about.bio.p12': 'Ce que j\'offre n\'est pas un programme. C\'est un espace — sans précipitation, personnel, construit autour de l\'endroit où vous êtes réellement. J\'écoute votre musique. Je vous écoute aussi. Ces deux choses ne sont pas séparées.',
    'about.bio.p13': 'Je ne suis pas arrivé à cela d\'en haut. Je viens du même endroit où vous vous tenez maintenant.',
    'about.bio.p14': 'Si cela résonne avec ce que vous cherchiez — vous êtes au bon endroit.',
    'about.lineage.label': 'Héritage et influences',
    'about.lineage.p1': 'Mes influences ne tiennent pas dans un genre précis. Elles vivent dans l\'espace entre les choses — la pause avant un drop, le silence qui fait qu\'un son paraît plus vaste qu\'il n\'est, le moment dans un morceau où le temps semble ralentir et respirer.',
    'about.lineage.p2': 'J\'ai grandi entre deux langues, deux cultures, deux manières d\'entendre le monde. Cet espace intermédiaire n\'a jamais semblé être un vide. Il ressemblait à une porte. La sensibilité française m\'a appris la retenue. La musique dont je suis tombé amoureux — mélodique, hypnotique, émotionnellement vaste — m\'a appris qu\'on peut toucher à la fois une piste de danse et une âme.',
    'about.lineage.p3': 'Mes productions sont autant façonnées par le cinéma que par la musique électronique. Par l\'architecture du son — comment l\'atmosphère se construit couche par couche, comment l\'émotion habite la texture et le temps plutôt que la seule mélodie. Je suis attiré par la musique qui ne se fait pas remarquer immédiatement, mais qui s\'installe en vous lentement, récompensant l\'écoute attentive que la plupart des gens ont oubliée.',
    'about.lineage.p4': 'Je n\'ai pas étudié la musique de manière formelle. J\'ai étudié le ressenti — à travers des années passées à m\'asseoir avec des émotions difficiles, à prêter attention à ce qui me touchait et pourquoi, à apprendre à rester présent quand le processus créatif devenait inconfortable. Cette pratique est tissée dans chaque session que je conduis. C\'est ce qui rend le travail réellement vivant.',
    'about.bridge': 'Si tout cela résonne — pas dans votre esprit, mais quelque part plus profondément —',
    'about.bridge.cta': 'Explorer Le Parcours',

    /* ── the-journey.html ── */
    'journey.label': 'Le Parcours',
    'journey.heading': 'Formation pour artistes<br>Prêts à arrêter de jouer un rôle et à commencer à arriver.',
    'journey.microcopy': 'Ce n\'est pas une éducation. C\'est une excavation.',
    'journey.phil.p1': 'La plupart des formations artistiques se concentrent sur la technique, le public et le résultat.',
    'journey.phil.p2': 'Ce travail se concentre sur quelque chose de plus profond : qui vous êtes quand vous créez.',
    'journey.phil.p3': 'Le Parcours est un passage guidé à travers deux territoires — de la découverte de votre fondation créative et de la reconnexion à votre voix authentique, jusqu\'à l\'habitation de la présence à travers le son et la construction de quelque chose qui vous appartient entièrement.',
    'journey.phil.p4': 'Ce n\'est pas pour tout le monde. C\'est pour les artistes qui sentent déjà que leur prochaine évolution n\'est pas technique.',
    'journey.gains.title': 'Ce qui change quand vous faites ce travail',
    'journey.gains.1': 'Une meilleure compréhension de qui vous êtes lorsque vous créez — et pourquoi cela compte plus que toute technique',
    'journey.gains.2': 'La capacité à terminer ce que vous commencez, parce que vous ne créez plus contre vous-même',
    'journey.gains.3': 'Un son reconnaissable — non pas assemblé à partir de références, mais construit à partir de ce que vous portez réellement',
    'journey.gains.4': 'La confiance pour rester avec l\'incertitude dans le processus créatif sans abandonner le travail',
    'journey.gains.5': 'Une relation avec la musique durable — non pas motivée par le résultat, mais par une présence authentique',
    'journey.mod1.label': 'Module I',
    'journey.mod1.title': 'Création Enracinée',
    'journey.mod1.tagline': 'Découvrez votre fondation créative — une seule session pour reconnecter avec votre voix authentique.',
    'journey.mod1.body1': 'Une session de découverte de 2 heures pour les nouveaux étudiants. Ensemble, nous explorons vos influences, construisons un projet à partir de zéro dans Logic Pro ou la DAW de votre choix, et définissons votre direction sonore.',
    'journey.mod1.body2': 'Vous repartez avec un titre de référence, un brief créatif définissant votre identité d\'artiste, et une feuille de route pour les prochaines étapes.',
    'journey.mod1.transform': 'De partir de rien \u00a0→\u00a0 à construire à partir de ce que vous portez réellement.',
    'journey.mod1.format': 'Session unique \u00a0·\u00a0 2 heures \u00a0·\u00a0 1-à-1 \u00a0·\u00a0 £69',
    'journey.mod1.cta': 'Explorer le Module I',
    'journey.mod2.label': 'Module II',
    'journey.mod2.title': 'Présence &amp; Son',
    'journey.mod2.tagline': 'Construire la profondeur par la pratique hebdomadaire — créer un titre complet qui est entièrement le vôtre.',
    'journey.mod2.body1': 'Quatre sessions hebdomadaires en 1-à-1 qui vous accompagnent de l\'ancrage et de l\'écoute à la conception de vos propres sons et à la réalisation d\'une composition complète. Chaque semaine s\'appuie sur la précédente.',
    'journey.mod2.body2': 'Vous repartez avec un titre de référence terminé, une palette sonore personnelle, un journal d\'écoute, et un accès direct à Eric tout au long via téléphone et WhatsApp.',
    'journey.mod2.transform': 'D\'idées dispersées \u00a0→\u00a0 à une création cohérente, ancrée dans qui vous êtes.',
    'journey.mod2.format': '4 sessions hebdomadaires \u00a0·\u00a0 1-à-1 \u00a0·\u00a0 Support asynchrone \u00a0·\u00a0 £199/mois',
    'journey.mod2.cta': 'Explorer le Module II',
    'journey.space.label': 'L\'Espace',
    'journey.fit.yes.title': 'Cet espace est pour les artistes qui\u00a0—',
    'journey.fit.yes.1': 'Cherchent une transformation personnelle à travers leur travail créatif',
    'journey.fit.yes.2': 'Veulent apprendre la production musicale depuis la base tout en développant leur voix unique',
    'journey.fit.yes.3': 'Sont prêts à élargir leur créativité et à construire un univers sonore cohérent',
    'journey.fit.yes.4': 'Sont prêts à ralentir pour aller plus profond',
    'journey.fit.yes.5': 'Sont attirés par cette page pour des raisons qu\'ils ne savent peut-être pas encore formuler',
    'journey.fit.no.title': 'Ce n\'est pas le bon espace si vous\u00a0—',
    'journey.fit.no.1': 'Cherchez uniquement des techniques de production sans le travail intérieur',
    'journey.fit.no.2': 'Voulez développer votre audience ou vos chiffres de streaming',
    'journey.fit.no.3': 'Avez besoin de validation externe pour continuer à créer',
    'journey.fit.no.4': 'N\'êtes pas prêt à investir du temps dans une pratique hebdomadaire',
    'journey.fit.no.5': 'Voulez un programme sans découverte créative de soi',
    'journey.apply.p1': 'L\'inscription se fait uniquement sur candidature.',
    'journey.apply.p2': 'Il ne s\'agit pas de filtrer. Il s\'agit de s\'assurer que l\'espace contient ce qu\'il doit contenir.',
    'journey.apply.btn': 'Postuler',

    /* ── apply.html ── */
    'apply.label': 'Candidature',
    'apply.heading': 'Commencez ici.',
    'apply.subheading': 'Avant de commencer à travailler ensemble, quelques questions — si ce travail résonne en vous, vous êtes chaleureusement invité·e à postuler. Il n\'y a aucune attente — seulement une conversation.',
    'apply.microcopy': 'Il n\'y a pas de bonnes réponses. Seulement des réponses honnêtes.',
    'apply.step1.q': 'Quel est votre nom et votre nom d\'artiste ?',
    'apply.step1.hint': 'S\'ils sont identiques, c\'est très bien.',
    'apply.step1.name': 'Votre nom',
    'apply.step1.artist': 'Nom d\'artiste (si différent)',
    'apply.step2.q': 'Décrivez votre pratique créative en quelques phrases.',
    'apply.step2.hint': 'Que faites-vous ? Depuis combien de temps ?',
    'apply.step2.placeholder': 'Je crée...',
    'apply.step3.q': 'Où en êtes-vous dans votre vie artistique en ce moment ?',
    'apply.step3.hint': 'Pas votre carrière — votre relation intérieure à la création.',
    'apply.step3.placeholder': 'En ce moment je suis...',
    'apply.step4.q': 'Qu\'est-ce qui vous a amené à cette page ?',
    'apply.step4.hint': 'Soyez aussi précis ou abstrait que vous le souhaitez.',
    'apply.step4.placeholder': 'Je suis arrivé ici parce que...',
    'apply.step5.q': 'Qu\'est-ce qui devrait changer dans votre vie pour faire de la place à ce type de travail au cours des 4 à 6 prochaines semaines ?',
    'apply.step5.placeholder': 'Pour faire de la place, j\'aurais besoin de...',
    'apply.step6.q': 'Quel module résonne le plus en ce moment ?',
    'apply.step6.mod1': 'Module 1 — Création Enracinée — £69',
    'apply.step6.mod2': 'Module 2 — Présence &amp; Son — programme de 4 semaines — £199',
    'apply.step6.unsure': 'Je ne suis pas encore sûr — j\'aimerais être guidé',
    'apply.step7.q': 'Comment avez-vous trouvé cet espace ?',
    'apply.step7.youtube': 'YouTube',
    'apply.step7.streaming': 'Spotify / Apple Music',
    'apply.step7.friend': 'Un ami ou collaborateur',
    'apply.step7.social': 'Les réseaux sociaux',
    'apply.step7.other': 'Autre chose',
    'apply.step7.other-placeholder': 'Si autre chose, comment ?',
    'apply.step8.q': 'Comment peut-on vous contacter ?',
    'apply.step8.email': 'Adresse email',
    'apply.step8.conv': 'Comment préféreriez-vous avoir une conversation ?',
    'apply.step8.video': 'Appel vidéo',
    'apply.step8.voice': 'Appel vocal',
    'apply.step8.written': 'Échange écrit',
    'apply.step9.q': 'Y a-t-il autre chose que vous souhaitez partager avant de commencer ?',
    'apply.step9.hint': 'C\'est facultatif.',
    'apply.btn.back': 'Retour',
    'apply.btn.continue': 'Continuer',
    'apply.btn.submit': 'Envoyer la candidature',
    'apply.confirm.heading': 'Merci.',
    'apply.confirm.p1': 'Vous recevrez une réponse dans les 7 jours.',
    'apply.confirm.p2': 'S\'il y a une correspondance, nous programmerons une conversation. Dans le cas contraire, vous recevrez une réponse honnête et respectueuse.',
    'apply.confirm.microcopy': 'Pas de réponses automatiques. Chaque candidature est lue personnellement.',
    'apply.confirm.return': 'Retourner à la musique',

    /* ── module-1.html ── */
    'm1.label': 'Module I',
    'm1.title': 'Création Enracinée',
    'm1.microcopy': 'Découvrez votre fondation créative — une seule session pour commencer.',
    'm1.where-begin.h': 'Où vous commencez',
    'm1.where-begin.p1': 'Vous ressentez l\'élan de créer, mais les outils vous semblent étrangers, ou les sons vers lesquels vous vous tournez ne semblent pas vraiment vôtres. Peut-être partez-vous complètement de zéro.',
    'm1.where-begin.p2': 'Il existe un écart entre qui vous êtes et ce que vous créez — et vous êtes prêt·e à le combler.',
    'm1.where-leads.h': 'Où cela mène',
    'm1.where-leads.p1': 'Lors d\'une seule session de 2 heures, vous reconnectez avec votre voix créative authentique — explorant votre identité, vos influences et ce qui se cache en dessous d\'elles.',
    'm1.where-leads.p2': 'Vous repartez avec un premier projet construit de zéro dans Logic Pro, un sens plus clair de votre direction artistique, et un résumé écrit de vos prochaines étapes.',
    'm1.session.title': 'Ce qui se passe pendant la session',
    'm1.part1.label': 'Partie 1',
    'm1.part1.theme': 'Exploration',
    'm1.part1.desc': 'Nous commençons par découvrir votre voix authentique : explorer votre créativité, vos influences passées et ce qui se cache derrière elles. Trouver l\'identité artistique et les références qui vous appartiennent vraiment.',
    'm1.part2.label': 'Partie 2',
    'm1.part2.theme': 'Création',
    'm1.part2.desc': 'Vous apprenez à créer un projet à partir de zéro dans Logic Pro. Je vous montre les techniques pour commencer à mettre vos idées en forme : configuration de session, flux du signal et fondamentaux pour construire le son à partir de rien.',
    'm1.part3.label': 'Partie 3',
    'm1.part3.theme': 'Premiers Mouvements',
    'm1.part3.desc': 'Traduire vos intuitions en son. Expérimenter avec des compositions initiales qui reflètent votre paysage émotionnel unique — doucement, sans jugement, sans référence extérieure.',
    'm1.walkaway.label': 'Ce que vous repartez avec',
    'm1.walkaway.1': 'un morceau de référence reflétant votre identité sonore émergente',
    'm1.walkaway.2': 'un premier projet Logic Pro commencé de zéro — votre tout premier croquis sonore',
    'm1.walkaway.3': 'un résumé enregistré de la session capturant vos insights, références et direction',
    'm1.walkaway.4': 'clarté sur vos 3 influences principales et comment les traduire dans votre propre son',
    'm1.walkaway.5': 'un brief créatif — document d\'une page définissant votre identité d\'artiste, votre ambiance et votre direction sonore',
    'm1.walkaway.6': 'une feuille de route pour vos prochaines étapes — sur quoi travailler dans les semaines à venir',
    'm1.walkaway.7': 'la confiance d\'avoir quelque chose de réel sur lequel construire',
    'm1.after.label': 'Après ce module, vous pourrez :',
    'm1.after.1': 'compléter un premier morceau terminé',
    'm1.after.2': 'comprendre votre langage harmonique',
    'm1.after.3': 'développer une identité sonore personnelle',
    'm1.container.label': 'Le cadre',
    'm1.container.format-label': 'Format',
    'm1.container.format-value': '1-à-1<br>avec Eric',
    'm1.container.duration-label': 'Durée',
    'm1.container.duration-value': 'Session unique<br>2 heures',
    'm1.container.prereq-label': 'Prérequis',
    'm1.container.prereq-value': 'Aucun — c\'est<br>ici que vous commencez',
    'm1.investment.label': 'Investissement',
    'm1.investment.price': '£69',
    'm1.investment.desc': 'Une session de découverte de 2 heures. Vous repartez avec un projet entamé, un résumé écrit et des étapes claires pour la suite.',
    'm1.investment.microcopy': 'C\'est le point d\'entrée dans Le Parcours — aucun prérequis, aucun engagement au-delà de cette session.',
    'm1.investment.btn': 'Réserver Module I',
    'm1.back': 'Tous les Modules',

    /* ── module-2.html ── */
    'm2.label': 'Module II',
    'm2.title': 'Présence &amp; Son',
    'm2.microcopy': 'Quatre semaines de profondeur, de pratique et de présence — construire un morceau qui est entièrement le vôtre.',
    'm2.where-begin.h': 'Où vous commencez',
    'm2.where-begin.p1': 'Vous disposez désormais de la fondation posée dans le Module I. Vous comprenez vos outils, vous pouvez façonner le son. Maintenant, vous êtes prêt·e à aller plus loin — à cultiver une véritable connexion au son à travers la conscience et la présence.',
    'm2.where-begin.p2': 'Les techniques sont là. Ce qui est nécessaire maintenant, c\'est la profondeur, la pratique et la patience pour laisser émerger quelque chose de complet.',
    'm2.where-leads.h': 'Où cela mène',
    'm2.where-leads.p1': 'Un morceau achevé — conçu comme une pièce de référence pour votre parcours musical. Vous utiliserez les techniques et outils du Module I pour façonner votre son unique, en travaillant depuis une présence incarnée plutôt que depuis des habitudes réactives.',
    'm2.where-leads.p2': 'À la fin, vous n\'avez pas seulement appris — vous avez créé quelque chose qui est entièrement vôtre.',
    'm2.weeks.title': 'Ce qui se passe pendant la formation',
    'm2.week1.label': 'Semaine 1',
    'm2.week1.theme': 'Arrivée',
    'm2.week1.desc': 'Ancrage dans le moment présent, création d\'une base solide pour le travail créatif à venir. Vous repartez avec un rituel d\'ancrage à répéter avant chaque session de production et un modèle de session Logic Pro configuré selon votre workflow.',
    'm2.week2.label': 'Semaine 2',
    'm2.week2.theme': 'Écoute',
    'm2.week2.desc': 'Écoute active avant de façonner les sons. Vous créez un journal d\'écoute personnel — un rapport annoté sur 1 à 3 morceaux de référence analysés sur le plan sonore. Comprendre comment atmosphère, espace et émotion sont construits dans votre musique préférée ou vos propres créations.',
    'm2.week3.label': 'Semaine 3',
    'm2.week3.theme': 'Corps',
    'm2.week3.desc': 'Exploration de l\'influence du mouvement et de la physicalité sur votre expression créative. Vous créez une palette sonore complète — un dossier de sons originaux, d\'échantillons et de textures que vous avez conçus, accompagné des samples que je partage avec vous. Premier brouillon d\'arrangement d\'un morceau construit autour de ces sons.',
    'm2.week4.label': 'Semaine 4',
    'm2.week4.theme': 'Intégration',
    'm2.week4.desc': 'Fusion de tous les éléments pour créer un morceau de référence complet — une composition entière représentant votre univers sonore. Vous recevez un enregistrement de feedback de ma part, annoté avec des repères temporels, ainsi qu\'un document de réflexion résumant votre parcours, vos découvertes et la prochaine étape.',
    'm2.walkaway.label': 'Ce que vous repartez avec',
    'm2.walkaway.1': 'un rituel d\'ancrage ou une pratique pré-session à répéter avant chaque session de production',
    'm2.walkaway.2': 'un modèle de session Logic Pro configuré selon votre workflow',
    'm2.walkaway.3': 'un journal d\'écoute personnel — analyse annotée des morceaux de référence',
    'm2.walkaway.4': 'une palette sonore complète — sons originaux, échantillons et textures conçus par vous',
    'm2.walkaway.5': 'un morceau de référence complet — composition entière représentant votre univers sonore',
    'm2.walkaway.6': 'un enregistrement de feedback avec annotations temporelles',
    'm2.walkaway.7': 'un document de réflexion sur vos progrès, vos découvertes et vos prochaines étapes',
    'm2.walkaway.8': 'un accès direct à Eric via téléphone et WhatsApp pour un support asynchrone tout au long du module',
    'm2.after.label': 'Après ce module, vous pourrez :',
    'm2.after.1': 'disposer d\'un morceau de référence et d\'un modèle utilisable pour tous vos projets',
    'm2.after.2': 'comprendre votre langage harmonique',
    'm2.after.3': 'développer une identité sonore personnelle',
    'm2.after.4': 'concevoir une palette sonore complète pour créer EPs et albums',
    'm2.after.5': 'recevoir des feedbacks constants de ma part quand nécessaire',
    'm2.container.label': 'Le cadre',
    'm2.container.format-label': 'Format',
    'm2.container.format-value': '1-à-1<br>avec Eric',
    'm2.container.duration-label': 'Durée',
    'm2.container.duration-value': '4 sessions<br>hebdomadaires',
    'm2.container.prereq-label': 'Prérequis',
    'm2.container.prereq-value': 'Module I ou<br>profondeur équivalente',
    'm2.investment.label': 'Investissement',
    'm2.investment.price': '£199<span style="font-size: 1rem; color: var(--text-muted);">/mois</span>',
    'm2.investment.desc': 'Quatre sessions hebdomadaires en 1-à-1 avec Eric. Vous repartez avec un morceau de référence terminé, une palette sonore personnelle et un support asynchrone direct tout au long du module.',
    'm2.investment.microcopy': 'Si le coût est un réel obstacle mais que la motivation est présente, nous pouvons en discuter.',
    'm2.investment.btn': 'Postuler pour le Module II',
    'm2.back': 'Tous les Modules',
  }
};

/* ============================================================
   APPLY LANGUAGE
   ============================================================ */
function applyLanguage(lang) {
  const t = translations[lang];
  if (!t) return;

  // Update <html> lang attribute and data-lang
  document.documentElement.lang = lang;
  document.documentElement.setAttribute('data-lang', lang);

  // Text content
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.textContent = t[key];
  });

  // HTML content (for elements with inline HTML like <em>, <br>)
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const key = el.getAttribute('data-i18n-html');
    if (t[key] !== undefined) el.innerHTML = t[key];
  });

  // Placeholders
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (t[key] !== undefined) el.placeholder = t[key];
  });

  // Save preference
  localStorage.setItem('lang', lang);
}

/* ============================================================
   INIT
   ============================================================ */
(function () {
  const saved = localStorage.getItem('lang') || 'en';
  applyLanguage(saved);

  // Wire up both toggles (desktop + mobile)
  ['langToggle', 'langToggleMobile'].forEach(id => {
    const btn = document.getElementById(id);
    if (!btn) return;
    btn.addEventListener('click', () => {
      const current = localStorage.getItem('lang') || 'en';
      applyLanguage(current === 'en' ? 'fr' : 'en');
    });
  });
})();
